version: "1.0"
services:
  clash:
    image: shelchin/clash:v1.18.0
    container_name: clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - 9090:9090
      - 7890:7890
    mem_limit: ${CLASH_MEM_LIMIT:-64m}
    restart: always
  dashboard:
    image: haishanh/yacd
    restart: always
    environment:
      - YACD_DEFAULT_BACKEND=http://192.168.50.52:9090
    ports:
      - "1234:80"